version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      private-net:
        aliases:
          - local.redis

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      private-net:
        aliases:
          - local.file-api

networks:
  private-net:
    external: true
