version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app_file
    networks:
      private-net:
        aliases:
          - local.file-api

networks:
  private-net:
    external: true
